services:
  validator:
    build:
      context: ./service1_validator
      dockerfile: Dockerfile_service1
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data

  welcome-letter:
    build:
      context: ./service2_welcome
      dockerfile: Dockerfile_service2
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data
      - ./output:/app/output

  offer-letter:
    build: 
      context: ./service3_offer
      dockerfile: Dockerfile_service3
    ports:
      - "5003:5003"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
