FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY service2_welcome.py .
COPY templates ./templates

EXPOSE 5002

CMD ["python", "service2_welcome.py"]